import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { getSessions, saveSession, updateSession } from "../db.js";

export function registerSessionTools(server: McpServer) {
  server.tool(
    "get_sessions",
    `Returns the recent session index.
DB PROTOCOL: call this at the start of a conversation before doing project work. The DB is the persistent source of truth for continuity.
Use sessions to detect whether this is a continuation, identify the active project, then load project memory with get_project, build_context, or search_all.
Sessions are compact indexes, not transcripts and not token-aware. Keep limit low. Recommended limit: 20.`,
    {
      limit: z
        .number()
        .optional()
        .describe("Number of sessions to return (default: 20). Keep low: sessions are not token-aware."),
    },
    async ({ limit }) => {
      const sessions = getSessions(limit ?? 20);
      return {
        content: [{ type: "text", text: JSON.stringify(sessions, null, 2) }],
      };
    },
  );

  server.tool(
    "save_session",
    `Creates a new session index.
Use when starting work that should be resumable later.
The summary must be dense and compact (~300 tokens max): active goal, important decisions, useful context, current state.
Do not store chat transcript or narrative. Store only durable continuity facts.`,
    {
      title: z.string().describe("Descriptive session title generated by the agent"),
      summary: z.string().describe("Dense session summary (~300 tokens max); never store a full transcript"),
      project_id: z.string().optional().describe("Project ID this session belongs to"),
    },
    async ({ title, summary, project_id }) => {
      const id = saveSession(title, summary, project_id);
      return {
        content: [{ type: "text", text: JSON.stringify({ id }) }],
      };
    },
  );

  server.tool(
    "update_session",
    `Updates an existing session summary.
Replace the full summary with a compact current index. Do not append indefinitely.
Use during long work or at checkpoint time when the persistent session state changed.`,
    {
      id: z.string().describe("Session ID to update"),
      summary: z.string().describe("New compact summary; replaces the previous one"),
    },
    async ({ id, summary }) => {
      updateSession(id, summary);
      return {
        content: [{ type: "text", text: "Session updated." }],
      };
    },
  );
}
